README.md
The following refers to an incorrect (old maybe?) way to create a model 
```javascript
const Card = new Model(table, {
name: 'Card',
fields: { /* Model schema field definitions */ }
})
```
This should be
```javascript
const Card = new Model(table, 'Card', {
fields: { /* Model schema field definitions */ }
})
```
=> typo in README 

src/Table.js
Version 1.0.1 
Error: "Cannot set property 'required' of undefined"
When using primary index that doesn't conform to { hash: 'pk', sort: 'sk' }
We have an existing DynamoDB table following the single table design pattern, that uses the following indexes:
```
primary: { hash: 'PK', sort: 'SK' },
"GSI1PK-GSI1SK-index":	{ hash: 'GSI1PK', sort: 'GSI1SK' },
"GSI2PK-index": { hash: 'GSI2PK'}
```
When evaluating OneTable on this table I receive the following error when instantiating the `Table` object:
```
"name":"TypeError",
"message": "Cannot set property 'required' of undefined",
"stack":"TypeError: Cannot set property 'required' of undefined at Model.prepModel node_modules/dynamodb-onetable/dist/mjs/Model.js:124:50
```
Here's the example code to reproduce
```
...
const indexes = {
primary: { …
```
=> Fix to resolve an error when creating a new table object that doesn't use default primary index format

src/index.js
Having been working locally without issue, I've now deployed to an AWS lambda function using the `node14.x` runtime. 
As I'm working in node14 my code uses import statements, rather than require. e.g. `import {Table, Model} from 'dynamodb-onetable';`
Invoking the lambda I receive an `ERR_MODULE_NOT_FOUND` not found error:
```
{
"errorType": "Error",
"errorMessage": "Cannot find module '/var/task/node_modules/dynamodb-onetable/dist/mjs/Expression' imported from /var/task/node_modules/dynamodb-onetable/dist/mjs/index.js",
"code": "ERR_MODULE_NOT_FOUND",
"stack": [
"Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/dynamodb-onetable/dist/mjs/Expression' imported from /var/task/node_modules/dynamodb-onetable/dist/mjs/index.js",
"    at finalizeResolution …
```
=> Fix for ERR_MODULE_NOT_FOUND within lambda node14.x runtime

src/Model.js
Discovered this error when setting a `limit` value param that is greater than the actual record count
=> Fix unmarshall failure when LastEvaluatedKey is empty

src/Model.js
It allows do: Model.find({ },{ }) without pasing Model.find({ _type: 'Role',  },{ });
````javascript
const RoleModel = new Model(table, 'Role', {
fields: {
pk: { value: '${_type}' },
sk: { value: '${_type}:${id}' },
id: { type: String, ulid: true, required: true },
name: { type: String, required: true },
permissions: { type: Array, required: true },
},
});
const roles = await RoleModel.find({ },{ limit: 3, parse: true });
`
=> Initialize typeField value for find method.

Dynamo/package.json
Not sure how it worked a month ago, but right now when trying to run app through serverless it throws me an error that `main` is not found. Shouldn't this path be similar as in `mjs` case?
=> fix: wrong path to dist file

package.json
Moved devDependencies that are actually used during runtime. Lack of it causes apps that are using this library to fail due to missing dependencies. Without this fix it works on developer machine.
Haven't tested it that way (it failed when I deployed app to AWS Lambda) is to use `npm install --production` on app that uses `dynamodb-onetable` locally. I have verified (manually and on limited scope) that this change helps.
=> chore: moved missing runtime deps

.github/workflows/build.yml
This change means that the test suite will be required to pass for both Node 12.x and Node 14.x based builds.
=> Enhancement: Run CI for Node 12 and Node 14

package-lock.json, package.json
Based on: https://github.com/sensedeep/dynamodb-onetable/pull/97#discussion_r690089307
- Ensure that npm is version 7
- Ensure that node is at least version 12.x
=> Maintenance: Specify node, and npm versions

.prettierrc, CONTRIBUTING.md, package-lock.json, package.json, test/utils/setup.ts
Morning @mobsense, and wow, thanks for this awesome library, I really enjoyed reading the docs and seeing the approach.
Your check-list for dynamoDB has gone straight onto my list of tools in notion :pray: 
- Adds docker support for running tests; this boots docker instead of a local dynamo-db for people without Java
- Adds a `.prettierrc` which enforces the documented coding standard in `CONTRIBUTING.md`
>Make sure your code style matches existing code. Soft tabs=4, no trailing spaces etc.
- Adds directions for install, build, test, and lint for contributors.
Please, let me know any feedback, and thanks for this tool :+1:
1. Setup a watcher to see what docker spawns
2. Run tests
3. Show docker spinning down afterward
=> Enhancement: Allow local forks to use docker to run dynamodb-local

src/Model.js, test/schemas/uniqueSchema.ts, test/unique.ts
When using an interpolated value as a unique attribute, this method was
saving `undefined` on the `pk`. This commit updates the logic to run the
interpolation before extracting the unique field value from properties.
This commit also adds a test for this case.
NOTE: It isn't clear that `new Expression` is required. Comments above
`prepareProperties` suggest that it is, but manual testing suggests
otherwise.
=> FIX: Handle interpolated values in createUnique

src/Model.d.ts
This is to fix the following issue.
https://github.com/sensedeep/dynamodb-onetable/issues/115
=> fix .find and .scan types

README.md, src/Expression.js, src/Model.d.ts, test/find.ts, test/params.ts
Allow substituting complex variables into where/set clauses using `@{}` brace style.
Substitutions are passed into params.substitutions and extracted into ExpressionAttributeValues.
Implements #119
=> Enhancement: Add `substitutions` to where clauses

README.md
I noticed what I believe is a minor inaccuracy in the table method usage documentation for the `fetch` method.
I appreciate your work to publish this excellent library for the community!
=> DOC: Update table method usage

src/Model.d.ts, src/Table.d.ts, test/pagination.ts, test/unique.ts
if you do
const result = await model.find({ some criteria })
you get Paged<Model>
but if you then do
result.(some array function such as filter, map, etc)(someCriteria)
you get any because you lose the typing.
This MR fixes that
=> Fix typing loss when executing array functions on paged

src/Model.d.ts
; cannot be in interfaces.
when i changed the interface the other day i left this because i was editing in github.
=> remove illegal character. ; cannot be on interfaces

src/Model.d.ts
The model definition does not have the `schema` option.
=> fix: Update model definition

src/Model.js
It looks like the when creating the item for the unique attribute `onetable` does not use the custom hash and sort keys.
=> fix: Fix unique attribute creation when hash and sort key are different

.gitignore, src/Table.d.ts, src/Table.js, test/typescript-tenant.ts
To be able to use `groupByType` we need to keep the `hidden` fields, there are cases where after we group the items we want those fields to not be present.
This PR adds the ability to provide `OneParams` to `groupByType` with `{parse:true, hidden:false}` so that the items are cleaned before they are added to a group.
=> Add support for params in group by

src/Model.js
If the prior item unique field and the new updated field are the same do not stop updating.
This case happens if you update the whole object not just some fields.
=> Handle unique fields that are the same as the prior version

README.md
The docs have a few inaccuracies around grouping / fetch:
1) Fetching a collection passing `fetch` an array of types shows the types pluralized in the result (which they are not).
2) `groupByType` requires `hidden: true` be included in the options to ensure `_type` is returned, otherwise the items will all be grouped under a single `_unknown` type.
=> Minor readme tweaks regarding groupByType usage

src/Model.d.ts, test/find.ts, test/schemas/defaultSchema.ts, test/utils/setup.ts
This addresses #220. I've included two commits:
* **The first makes running `npm test` more robust.** Before this change, for whatever reason, an initial test run would pass, but subsequent runs would fail. There was an issue with DynamoDB being unavailable. Now, both the local Java and Docker paths wait on the port.
* **The second introduces the new types for `find`.** There are probably other types we can improve, but I figure we can tackle those in separate pull requests. I added just a minimal test that the TypeScript types can be used (it's a "list" test that simulates how I use GSIs in my application).
=> Improve TypeScript types for find

src/Model.d.ts
Without providing a version the client throws an error
=> Make Schema.version required

src/Model.d.ts
In my local setup, the following code currently does not typecheck:
```typescript
import Dynamo from 'dynamodb-onetable/Dynamo'
import { Entity, Table } from 'dynamodb-onetable'
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
const client = new Dynamo({client: new DynamoDBClient({ apiVersion: '2012-08-10' })});
const schema = {
version: '0.0.1',
indexes: {
primary: { hash: 'pk', sort: 'sk' },
gs1:     { hash: 'gs1pk', sort: 'gs1sk', follow: true },
},
models: {
User: {
pk:          { type: String, value: 'account:${accountName}' },
sk:          { type: String, value: 'user:${email}', validate: /.*@.*/ },
id:          { type: String, required: true },
email:       { type: String, required: true },
role:        { type: String, enum: ['user', 'admin'], required: true, default: …
```
=> Feature: better enum typing

src/Model.js, test/timestamps.ts
When `timestamps: true` running an update with `set` and  `exists: null` causes the `set` values to be overwritten by the set of created at property.
=> fix: timestamps + exists: null causes set to be overwritten

src/Model.js
Remove unique is causing partial transaction execution.
This should fix it and it should behave the same as before for normal use cases.
=> Prevent partial transaction write

README.md
The provided example in the README shows how to apply a ```list_append``` into ```update.set``` operation. The old example incorrectly uses the ```+``` between arguments. That needed replacement with a ```,```. 
Furthermore we adjusted the example with a ```if_not_exists``` helper to be able to set the initial contact.
=> Correct and Adjust a syntax error in Javascript example in README

.github/workflows/build.yml, jest.config.js, package-lock.json, package.json, src/Model.d.ts, src/Model.js, src/Table.d.ts, src/Table.js, test/loader.ts, test/utils/init.ts
Original discussion https://github.com/sensedeep/dynamodb-onetable/discussions/250
In this PR I added the possibility to use https://www.npmjs.com/package/dataloader which allows to group all get requests made in parallel and perform a single BatchGetRequest.
For example (see tests for more) 
```js
// this will accumulate all gets request into a single batch request
// and return an array of items
const items = await Promise.all(
ids.map(id => model.load({ id })
);
```
```js
// this will perform a single batch get operation with just one item get and will return to each get the same value
// dynamo does not supports duplicate keys on batch request and the implementation will deal with that
const items = await Promise.all([
model.load({ id: 'same-id' }),
model.load({ id: 'same-id' }), …
```
=> feat: DataLoader

src/Model.d.ts
for this schema 
```
const ReactionsSchema = {
fields: {
likes: { type: Set },
dislikes: { type: Set },
}
}
```
when doing 
```
type Reactions = Entity<typeof ReactionsSchema.fields>;
```
the type of `Reactions.like` and `Reactions.dislikes` are resolved as `Set<{ type: Set }>`
=> fix Set type

src/index.js
I ran into an issue when using OneTable in ESM setup:
```
/.../node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383
throw new ERR_MODULE_NOT_FOUND(
^
CustomError: Cannot find module '/.../node_modules/dynamodb-onetable/dist/mjs/Error' imported from /.../node_modules/dynamodb-onetable/dist/mjs/index.js
```
=> fix module import

.eslintrc.js, .github/workflows/build.yml, package.json, src/Expression.js, src/Metrics.js, src/Model.js, src/Schema.js, src/Table.js, src/index.js, test/batch.ts, test/crypto.ts, test/loader.ts, test/mapping-and-packing.ts, test/unique.ts, test/utils/init.ts
- fixed logic for dataloader keys manipulation when client v2 vs v3 (v3 has `{S:''}` and v2 is `''`)
- run all tests both with v2 and v3
=> fix: dataloader keys manipulation logic when v2 vs v3

src/Table.d.ts
Table object has a very useful method `child` but typescript definition for it is missing.
=> Add Table.child typescript definition

src/Expression.js
The problem referenced in the comment:
> Except for numbers because we don't want to confuse valuesMap indexes. i.e. 7 vs "7" 
was still present if a number came first in the attribute list, i.e. `{"version": 1, "id": "1"}` - in this case you get id set to the number `1` instead of a string.
=> Add missing check for numeric value

src/Expression.js
Missing substitutions was being thrown if the substitution was supplied but falsy. This is particularly problematic when filtering on a boolean value.
=> fix: Allow substitutions to be falsy

README.md
I noticed that the `validation` regex was incorrect for the generated `ulid` field.
=> fix: ulid validation regex in example

README.md, src/Expression.js, src/Model.d.ts, test/params.ts
A shortcut on params to allow safe pushing to an array using `set ${target} = list_append(if_not_exists(${target}, ${empty}), ${items})`
This is a [very common approach](https://medium.com/@nehaguptag/append-to-dynamodb-list-golang-5ac7b3ec5559) on DynamoDB and I see myself repeating it many times in my codebase
From
```js
await User.update(
{ id: user.id },
{
set: { tokens: 'list_append(if_not_exists(${tokens}, @{empty}), @{token})' },
substitutions: { token: ["yellow"], empty: [] }
}
);
```
To
```js
await User.update(
{ id: user.id },
{ push: { tokens:  ["yellow"] }}
)
```
=> feat: push param shortcut

src/Model.js, test/schemas/uniqueSchema.ts, test/unique.ts
This was discussed a while ago: https://github.com/sensedeep/dynamodb-onetable/discussions/195 and partially supported. However, while optional values were fine on create, then would fail on update and delete in some cases.
I've tried to cover all the error cases in tests, but it's a little tricky since the tests aren't truly independent.
Builds on https://github.com/sensedeep/dynamodb-onetable/pull/313
=> Support optional unique values.

src/Model.js
It seems like `transformWriteSet` will always throw `OneTableError` error if there will be array of strings for a field with type=Set.
[This line](https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.js#L1535) is checking for `type == 'set'`, but `transformWriteSet` doesn't cover such case.
Example:
schema:
```
...
User: {
pk:         { type: String, value: 'account#${accountId}' },
sk:         { type: String, value: 'user#${email}' },
accountId:  { type: String, required: true },
id:         { type: String, generate: 'ulid', validate: Match.ulid },
name:       { type: String, required: true, validate: Match.name },
email:      { type: String, required: true, validate: Match.email, crypt: true },
role:       { type: String, default: 'user', enum: ['admin', 'user']},
guests: …
```
=> pass an array of strings for a `Set` field

src/Model.d.ts
This change will offer type hints for the object field type where a schema has been defined.
Currently you would see the following when accessing an object type property:
And trying to access the street property on an address would cause a type error:
With this change objects that have a schema are now type complete:
In a scenario where the `schema` field is not provided the type for an object field it would become `Entity<unknown>` which I think would be the correct behaviour.
=> Support types of nested objects

src/Model.d.ts
Currently, calls to `create` do not enforce that required parameters are present. `EntityParameters<T>` is wrapped in `Partial`, meaning all required parameters become optional.
So, for instance, with this config
```ts
import {Entity, Table} from 'dynamodb-onetable';
const Schema = {
version: '1.0.0',
indexes: {
primary: {hash: 'pk', sort: 'sk'},
gs1: {hash: 'gs1pk', sort: 'gs1sk'},
gs2: {hash: 'gs2pk', sort: 'gs2sk'},
},
models: {
User: {
pk: {type: String, value: 'USER#${name}'},
sk: {type: String, value: 'USER#${name}'},
name: {type: String, required: true, unique: true},
},
} as const,
params: {
timestamps: true,
isoDates: true,
createdField: 'createdAt',
updatedField: 'updatedAt',
},
};
type UserType = Entity<typeof Schema.models.User>;
const table = new Table({
name: 'user',
schema: …
```
=> fix(types): enforce schema requirements during model create

package.json, src/Model.js
At present nested schemas cannot have required fields with a non-required parent. For example
```
{
parent: {
type: 'object',
required: false,
schema: {
name:  {
type: 'string',
required: true
}
}
}
}
```
Fails validation when parent is undefined.  This minor PR is my best guess at how to resolve this. 
It also has a small fix so it will build on Windows.
=> Allow non-required objects with required fields

src/Table.d.ts, src/Table.js
Since the Table class already generates a definition description with createTable, it would be helpful to expose that functionality as a standalone method. When using infrastructure as code frameworks such as AWS CDK, Serverless, or Serverless Stack, this would be a great benefit to quickly generate the resource definition from a Onetable schema and table name. 
This pull request breaks the definition generation functionality of `Table.createTable()` out as `Table.getTableDefinition()`
Currently, the only way to do this programmatically is to mock a fake dynamodb client.
**Before:**
```javascript
const table = new Table({
name: 'DynamoTable',
schema: mySchema,
// Stub in a createTable used to describe the table
client: {
V3: true,
createTable(def) {
return def
},
},
})
const definition = …
```
=> Break table definition out as its own function

src/Model.js, test/find.ts
When passing the option `count: true` to `find()`/`scan()` the count results are not aggregated when the record set exceeds DB limits and requires paging to get all record counts. Instead, the count result of the last page is returned.
This fix simply adds a `count` aggregation variable to `run()` and uses that as the return result instead of `result.Count`, which is only the count of records from the last query.
Note: the test required creating a bunch of large records to exceed DynamoDB's scan size limit to ensure `run()` has to page through results. It's not that bad but it may make sense to flag this test off?
=> Fixes scan/find count aggregation when paging

README.md
```
const Dynamo = require('../node_modules/dynamodb-onetable/Dynamo');
const test = new Dynamo();
```
the above would give me the following error: `TypeError: Dynamo is not a constructor`. However, it was resolved with this small change
```
const {Dynamo} = require('../node_modules/dynamodb-onetable/Dynamo');
const test = new Dynamo();
```
=> i had this issue when trying it on my machine. this change fixed it

src/Model.d.ts, src/Table.d.ts
This change fixes the type declarations for the Model and Schema so that they _exclude_ `undefined` values. This is referenced in #393.
The error can be reproduced with a minimal project, here: https://github.com/skrud-dt/dynamodb-onetable-types-reproduce
The reason this is happening is that `'schema'` is defined on the `OneField` model as possibly being `undefined`, which causes TypeScript to complain about it. The workaround here is to just use `Exclude<T["schema"], undefined>` so that we're explicitly saying that "we want the type of `T["schema"]` that's not undefined".
To show that this works I fixed it in my reproduction example in this branch, using a patch. https://github.com/skrud-dt/dynamodb-onetable-types-reproduce/compare/main...fix-with-patch
=> fix(types): fix type error on models and table classes

src/Model.d.ts
per the docs, encode is supposed to follow a format of ['sk', '#', 1] which means it's a mix of strings and numbers
=> fix: OneField.encode typescript definition needs to allow for (string|number)

package-lock.json, package.json, src/Table.d.ts, src/Table.js, test/stream.ts
I needed to be able to take DynamoDB streams and get the OneTable model objects from the records.
The code should support New Image, Old Image and New And Old Image view types. Keys only is not supported but I guess in theory code could be added to fetch the item from dynamodb, I didn't need this so didn't build it.
I found the `Table.unmarshall` method for sdk v2 didn't support the format of the stream record so the extra `unmarshallStreamImage` method I added inside the `stream` method
=> Support for Converting DynamoDb stream records to New and Old model objects

src/Model.d.ts, test/typescript-types.ts
For javascript it just implicitly allows that as an option to the split method.
=> fix: Allow encode in typescript to use a RegExp for the deliminiter

src/Expression.js, src/Model.d.ts, src/Model.js, test/typescript-basic.ts
This enables writing conditional expressions on the transaction so that it fails if the conditions aren't met
=> feat: add support for ConditionCheck transaction items

src/Schema.js
needs to have the same logic applied to it as the field.validate
=> fix: saveSchema breaks when supporting RegExp for encode

jest.config.js, src/Table.js
From this discussion - https://github.com/sensedeep/dynamodb-onetable/discussions/445#discussioncomment-4987730
I've removed the use of the sdk v2 converter. As the stream records are the same structure no matter what sdk you use I've opted to use the v3 unmarshall method as there is already a hard dependency of the v3 library that contains the unmarshall method and it performs the same as the v2 version.
=> fix: replace sdk v2 unmarshaller

src/Model.d.ts
Fix TypeScript (v4.9.5) error
tsconfig.json:
```json
"compilerOptions": {
"target": "es2022",
"module": "commonjs",
"moduleResolution": "node",
"newLine": "lf",
"strict": true,
"strictPropertyInitialization": false,
"strictNullChecks": true,
"forceConsistentCasingInFileNames": true,
"allowSyntheticDefaultImports": true,
"esModuleInterop": true,
"resolveJsonModule": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"removeComments": true
}
```
build error:
=> FIX: oneschema array typings

src/Table.js
This one kept me up all week but I finally tracked down the issue. I was doing tests of batchWrites of 10000 items but it was never writing them all, would get to around 3,000 and start dropping items randomly. I spent ages rewriting our code thinking that could be the issue as the OneTable `batchWrite` method code looked fine. After exhausting that last night I rewrote the `batchWrite` method in typescript in our own code to go around the OneTable method and realised what the issue was.
It seems the handling of the response from the batchWrite expected there to be a `data` object in the response which there is not. This means `UnprocessedItems` was never found so never reprocessed. The blessings of typescript, it told me immediately that `data` didn't exist (why didn't I do this first? …
=> fix: incorrect handling of the `batchWrite` response meant unprocessed items never reprocessed

src/Metrics.js
The `metrics` config (line 189) is being shadowed by metrics var (line 208) and so namespace is never included in output
=> fix: Metrics not including Namespace

src/Metrics.d.ts, src/Model.d.ts, src/Table.d.ts
- fix: Add `profile` to OneParams type
- feat: Add table.metrics to TS definitions
=> Add missing Metrics types

src/Model.d.ts
When defining an object, it is useful to be able to not define the schema for the object and leave it open.  We use this often for key value maps of non critical data, usually we use `facts` as the field name for this.  e.g.
```
[...]
facts: {
type: 'object',
required: true
},
[...]
```
However, this results in facts being considered `unknown` and therefore not assignable or accessible without tricks such as type predicates or type assertions.  For example, this gives a typescript syntax highlighting error in vscode like:
```
resource.facts.abc = '123'
Property 'facts' does not exist on type 'Flatten<Merge<Required<unknown>, OptionalOrUndefined<unknown>>>'.
```
My overall preference would be to support more schema/type control over such open objects, however, that would be a much bigger …
=> Handle no schema on object fields as `Record<any, any>`

src/Model.js, test/find.ts, test/schemas/defaultSchema.ts
=> fix: log error on missing required fields when finding with fields selection

src/Model.d.ts, test/array-items.ts, test/schemas/arrayItemsSchema.ts
Assume we have the following schema:
```ts
export const TheSchema {
...,
models: {
SomeModel: {
brands: {
type: Array,
required: true,
items: {
type: String,
enum: Object.values(Brand)
}
}
}
}
}
```
the following Entity type:
```ts
export type SomeModelEntity = Entity<typeof TheSchema.models.SomeModel>;
```
and the following code:
```ts
const {brands}: SomeModelEntity = {
...
}
```
when we check the type of `brands` we're seeing that it has the type `string[]` instead of the type `Brand[]`
When we check the type of `brands` we'll see that it has type `Brand[]`
=> Add (multidimensional) enum array typing

src/Model.d.ts
This PR addresses https://github.com/sensedeep/dynamodb-onetable/issues/555
Issue: fields do not include a null type when nulls === true. 
Solution: Adjusted `src/Model.d.ts` to checking nulls param, only when required is not true.
=> fix: include null typing for nulls field param
